# Generated by Django 4.2.3 on 2023-08-09 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_news', models.CharField(max_length=150)),
                ('post_news', models.TextField()),
                ('topic_images', models.ImageField(upload_to='')),
                ('posted_time', models.DateField(auto_now=True)),
                ('posted', models.BooleanField()),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypage.login')),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('login_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypage.login')),
            ],
        ),
    ]
