# Generated by Django 4.2.3 on 2023-08-21 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdescripe',
            name='email',
        ),
    ]
