# Generated by Django 4.2.3 on 2023-08-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_alter_news_topic_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='posted',
            field=models.BooleanField(null=True),
        ),
    ]
